language: java

jdk:
  - openjdk8

sudo: false

services:
  - postgresql

before_install:
  - psql -c 'create database weater;' -U postgres

notifications:
  email:
    recipients:
      - ikioresko@gmail.com
    on_success: never # default: change
    on_failure: always # default: always